name: Publishing

# Run on every push to main, release or change on pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
  release:

permissions:
  contents: read

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Dependencies
          run: sudo apt install -y autoconf automake curl libtool llvm libclang-dev
        
        - name: Build
          run: ./mill compile

        - name: Publish
          # Only actually publish if new main commit or new tag
          if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
          env:
            MILL_PGP_SECRET_BASE64: ${{ secrets.PGP_SECRET_BASE64 }}
            MILL_PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
            MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
            MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          run: ./mill publishSonatypeCentral
