name: Publishing

# Run on every push to main and every change on pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Dependencies
          run: sudo apt install -y llvm libclang-dev
        
        - name: Build
          run: ./mill compile

        